export type ProductTelemetryEventType =
  | "home_opened"
  | "home_search_used"
  | "station_clicked"
  | "station_opened"
  | "submit_opened"
  | "submission_camera_opened"
  | "camera_opened_from_station"
  | "submission_started"
  | "submission_flow_opened"
  | "submission_context_autofilled"
  | "station_suggestion_shown"
  | "station_suggestion_accepted"
  | "station_suggestion_changed"
  | "station_last_used_reused"
  | "station_geo_state_reported"
  | "station_proposal_flow_opened"
  | "station_seed_flow_opened"
  | "station_seed_gps_ok"
  | "station_seed_gps_imprecise"
  | "station_seed_no_gps"
  | "station_seed_similar_chosen"
  | "station_seed_new_station_created"
  | "station_seed_new_station_active"
  | "station_seed_new_station_manual_review"
  | "station_seed_flow_abandoned"
  | "station_similar_choice_clicked"
  | "station_proposal_created"
  | "station_proposal_submitted_with_geo"
  | "station_proposal_submitted_without_geo"
  | "submission_station_step_abandoned"
  | "submission_flow_completed"
  | "submission_stage_abandoned"
  | "submission_step"
  | "submission_draft_restored"
  | "submission_photo_reselected"
  | "submission_photo_lost"
  | "submission_abandoned_before_photo"
  | "submission_abandoned_after_photo"
  | "submission_retry_clicked"
  | "submission_series_continued"
  | "submission_queue_added"
  | "submission_queue_retried"
  | "submission_queue_completed"
  | "submission_queue_discarded"
  | "submission_queue_recovered_success"
  | "submission_queue_item_expired"
  | "submission_queue_manual_retry"
  | "submission_queue_flush_started"
  | "submission_abandoned"
  | "submission_failed"
  | "submission_accepted"
  | "audit_opened"
  | "feedback_opened"
  | "beta_feedback_received"
  | "route_started"
  | "route_station_skipped"
  | "route_station_arrived"
  | "route_completed"
  | "route_abandoned"
  | "geolocation_granted"
  | "geolocation_denied"
  | "geolocation_error"
  | "mission_started"
  | "mission_completed"
  | "mission_aborted"
  | "mission_station_completed"
  | "mission_station_skipped"
  | "field_quality_warning_shown"
  | "submission_quality_flagged"
  | "external_navigation_opened"
  | "return_after_navigation"
  | "territorial_landing_visited"
  | "territorial_entry_from_landing"
  | "station_page_shared"
  | "station_evidence_viewed"
  | "hub_opened"
  | "hub_action_clicked"
  | "hub_mission_resumed"
  | "hub_pendency_resubmitted"
  | "hub_camera_opened"
  | "hub_conversion_success"
  | "rollout_recommendation_accepted"
  | "rollout_recommendation_rejected"
  | "rollout_manual_override"
  | "quick_action_misclick"
  | "group_landing_view"
  | "group_conversion_start"
  | "mission_start_from_group"
  | "operational_action_proposed"
  | "operational_action_accepted"
  | "operational_action_ignored"
  | "operational_action_executed"
  | "report_cycle_submitted"
  | "report_cycle_moderated"
  | "report_cycle_visible"
  | "home_block_interacted"
  | "territorial_default_rejected"
  | "quick_action_executed"
  | "hub_retention_view"
  | "hub_continuity_action"
  | "territorial_shared"
  | "share_link_opened"
  | "first_fold_action"
  | "hub_activation_click"
  | "first_submission_milestone"
  | "identity_prompt_shown"
  | "identity_prompt_saved"
  | "identity_prompt_dismissed"
  | "public_station_view"
  | "station_action_click"
  | "memory_shortcut_click"
  | "scroll_depth"
  | "submission_validation_error"
  | "submission_field_abandoned"
  | "inbox_opened"
  | "inbox_item_click"
  | "inbox_cleared"
  | "quick_action_clicked"
  | "hub_agenda_action_clicked"
  | "performance_mode_detected"
  | "low_perf_map_mounted";

export interface ProductTelemetryEventInput {
  eventType: ProductTelemetryEventType;
  pagePath: string;
  pageTitle?: string | null;
  stationId?: string | null;
  city?: string | null;
  fuelType?: string | null;
  scopeType?: string | null;
  scopeId?: string | null;
  reason?: string | null;
  payload?: Record<string, unknown>;
}



