export type ProductTelemetryEventType =
  | "home_opened"
  | "home_search_used"
  | "station_clicked"
  | "station_opened"
  | "submit_opened"
  | "submission_camera_opened"
  | "camera_opened_from_station"
  | "submission_started"
  | "submission_step"
  | "submission_draft_restored"
  | "submission_photo_reselected"
  | "submission_photo_lost"
  | "submission_abandoned_before_photo"
  | "submission_abandoned_after_photo"
  | "submission_retry_clicked"
  | "submission_series_continued"
  | "submission_queue_added"
  | "submission_queue_retried"
  | "submission_queue_completed"
  | "submission_queue_discarded"
  | "submission_queue_recovered_success"
  | "submission_queue_item_expired"
  | "submission_queue_manual_retry"
  | "submission_queue_flush_started"
  | "submission_abandoned"
  | "submission_failed"
  | "submission_accepted"
  | "audit_opened"
  | "feedback_opened"
  | "beta_feedback_received"
  | "route_started"
  | "route_station_skipped"
  | "route_station_arrived"
  | "route_completed"
  | "route_abandoned"
  | "geolocation_granted"
  | "geolocation_denied"
  | "geolocation_error"
  | "mission_started"
  | "mission_completed"
  | "mission_aborted"
  | "mission_station_completed"
  | "mission_station_skipped"
  | "field_quality_warning_shown"
  | "submission_quality_flagged"
  | "external_navigation_opened"
  | "return_after_navigation"
  | "territorial_landing_visited"
  | "territorial_entry_from_landing"
  | "station_page_shared"
  | "station_evidence_viewed"
  | "hub_opened"
  | "hub_action_clicked"
  | "hub_mission_resumed"
  | "hub_pendency_resubmitted"
  | "hub_camera_opened"
  | "hub_conversion_success"
  | "rollout_recommendation_accepted"
  | "rollout_recommendation_rejected"
  | "rollout_manual_override"
  | "quick_action_misclick"
  | "group_landing_view"
  | "group_conversion_start"
  | "mission_start_from_group"
  | "operational_action_proposed"
  | "operational_action_accepted"
  | "operational_action_ignored"
  | "operational_action_executed"
  | "report_cycle_submitted"
  | "report_cycle_moderated"
  | "report_cycle_visible"
  | "home_block_interacted"
  | "territorial_default_rejected"
  | "quick_action_executed"
  | "hub_retention_view"
  | "hub_continuity_action"
  | "territorial_shared"
  | "share_link_opened";

export interface ProductTelemetryEventInput {
  eventType: ProductTelemetryEventType;
  pagePath: string;
  pageTitle?: string | null;
  stationId?: string | null;
  city?: string | null;
  fuelType?: string | null;
  scopeType?: string | null;
  scopeId?: string | null;
  reason?: string | null;
  payload?: Record<string, unknown>;
}
